// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ncrzkezrfgeflsgwurig.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5jcnprZXpyZmdlZmxzZ3d1cmlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3MDcxODMsImV4cCI6MjA3MjI4MzE4M30.Dvk_8Xw1d9ra4WWv2lDXECAgCRJZrG9vmLeM_9nM5T8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});